name: Ping Render App

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl the site
        run: curl -s https://ticketformv1.onrender.com/ > /dev/null
